### ISSUE TITLE
Courses not updated after closing and re-opening tab

### ISSUE THREAD

**Issue by notfin** [theRoughCode/WatsMyMajor#139]
When saving courses to my courses, none of the new ones are saved, and it reverts back to the old calendar when the page is refreshed

**Comment by theRoughCode** [comment]
Could you detail the steps you took?  I tried searching for a course -> add to cart.  It does appear in the "cart" section of my courses which I can then drag into my term boards.
Also, what do you mean by "old calendar"?  Do you mean your courses?  A screenshot would be super helpful too!

**Comment by notfin** [comment]
I mean, I tried to plan my courses and had them planned up to 3A, and then
closed and opened the page again and they were gone. I tried again and then
refreshed and they were gone again.

пт, 29 марта 2019 г. в 10:00, Raphael Koh <notifications@github.com>:

**Comment by theRoughCode** [comment]
@notfin what browser are you using?  I tried closing the browser after changing my schedule and you're right, it does not update.  However, if you refresh the page without changing it, it will be updated.  I assume that this is because the browser is using the cached data and has not pulled in the updated data.  I will log an issue to fix this. 

Let me know if this works (i.e. after closing and re-opening, don't move anything around as it will reset your courses, but just refresh the page).

**Comment by brijendra98** [comment]
@theRoughCode So, I faced a similar issue right now where I dragged a course from a "term" to delete it (or drag it from a term to cart o one term to another term). This change is reflected on the UI side but is not getting updated on the back-end because:

- On refreshing the page, its back to the state before I made changes. Same behaviour on re-logging etc.
- Further inspecting the console logs, it appears that the API request which was made while moving a course returned a 400 response due to which the course movement between a term and (another term/cart) did not really take place on the server side.

**Comment by theRoughCode** [comment]
@brijendra98 Thanks for the detailed response!  I'll take a look at it ASAP.  Did you have any empty terms?  A screenshot would also be super helpful.

**Comment by theRoughCode** [comment]
@brijendra98 I couldn't replicate your error.  Could you send me a screenshot together with a screenshot of the 400 response?

**Comment by brijendra98** [comment]
@theRoughCode Sorry for the delay. Here is a screen video recording of the entire flow I am facing this problem with. Please let me know if you need the exact HTTP curl call or something

https://drive.google.com/file/d/1V6Hy7paEi-C8tGCorxUi4g6_LKLO6tVQ/view?usp=sharing

**Comment by theRoughCode** [comment]
This should have been fixed by the [latest commit](https://github.com/theRoughCode/WatsMyMajor/commit/e8241e03d473e59beb895212d3b8f8707f6574a7).
